backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "technology"
    label: "Technology"
    folder: "src/pages/technology"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    fields:
      - label: "Template"
        name: "template"
        widget: "hidden"
        default: "page"

      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "blog"

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Category"
        name: "category"
        widget: "select"
        options: ["Technology", "Fashion", "Outdoors"]

      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"

      - label: "Slug"
        name: "slug"
        widget: "string"

      - label: "Meta Title"
        name: "metaTitle"
        widget: "string"
        required: false

      - label: "Meta Description"
        name: "metaDescription"
        widget: "text"
        required: false

      - label: "Body"
        name: "body"
        widget: "markdown"
        buttons: ["bold", "italic", "link"]

      - label: "Publish Date"
        name: "date"
        widget: "datetime"

  - name: "fashion"
    label: "Fashion"
    folder: "src/pages/fashion"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    fields:
      - label: "Template"
        name: "template"
        widget: "hidden"
        default: "page"

      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "blog"

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Category"
        name: "category"
        widget: "select"
        options: ["Technology", "Fashion", "Outdoors"]

      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"

      - label: "Slug"
        name: "slug"
        widget: "string"

      - label: "Meta Title"
        name: "metaTitle"
        widget: "string"
        required: false

      - label: "Meta Description"
        name: "metaDescription"
        widget: "text"
        required: false

      - label: "Body"
        name: "body"
        widget: "markdown"

      - label: "Publish Date"
        name: "date"
        widget: "datetime"

  - name: "outdoors"
    label: "Outdoors"
    folder: "src/pages/outdoors"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    fields:
      - label: "Template"
        name: "template"
        widget: "hidden"
        default: "page"

      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "blog"

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Category"
        name: "category"
        widget: "select"
        options: ["Technology", "Fashion", "Outdoors"]

      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"

      - label: "Slug"
        name: "slug"
        widget: "string"

      - label: "Meta Title"
        name: "metaTitle"
        widget: "string"
        required: false

      - label: "Meta Description"
        name: "metaDescription"
        widget: "text"
        required: false

      - label: "Body"
        name: "body"
        widget: "markdown"

      - label: "Publish Date"
        name: "date"
        widget: "datetime"
